apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: ml-predictions 
  name: ml-predictions
spec:
  replicas: 2
  selector:
    matchLabels:
      service: ml-predictions
  template:
    metadata:
      labels:
        service: ml-predictions
        api: external
    spec:
      containers:
      - name: ml-predictions
        imagePullPolicy: Always
        image: folasade/demolocal:latest
        command: ["python3",  "app.py"]
        ports:
        - containerPort: 8000
